"""add rating table

Revision ID: 057940d75196
Revises: c3cd2ab65ce5
Create Date: 2024-08-08 10:46:05.586163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057940d75196'
down_revision = 'c3cd2ab65ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('review_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fk_business_id', sa.CHAR(length=36), nullable=True),
    sa.Column('fk_rater_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['fk_business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['fk_rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rating_rating_count'), ['rating_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_rating_count'))
        batch_op.drop_index(batch_op.f('ix_rating_id'))

    op.drop_table('rating')
    # ### end Alembic commands ###
