"""add business_category table

Revision ID: 27553768d6f8
Revises: e2499f08fdb3
Create Date: 2024-08-08 10:30:42.015990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27553768d6f8'
down_revision = 'e2499f08fdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_category_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_category_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_category_name'))
        batch_op.drop_index(batch_op.f('ix_business_category_id'))

    op.drop_table('business_category')
    # ### end Alembic commands ###
