"""add business table

Revision ID: c3cd2ab65ce5
Revises: 27553768d6f8
Create Date: 2024-08-08 10:37:01.919985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cd2ab65ce5'
down_revision = '27553768d6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('contact', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fk_business_category_id', sa.Integer(), nullable=True),
    sa.Column('fk_owner_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['fk_business_category_id'], ['business_category.id'], ),
    sa.ForeignKeyConstraint(['fk_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_name'))
        batch_op.drop_index(batch_op.f('ix_business_id'))

    op.drop_table('business')
    # ### end Alembic commands ###
