"""add user_needs table

Revision ID: c4659b16c143
Revises: 057940d75196
Create Date: 2024-08-08 10:51:06.027091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4659b16c143'
down_revision = '057940d75196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_needs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('fk_business_category_id', sa.Integer(), nullable=True),
    sa.Column('fk_user_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['fk_business_category_id'], ['business_category.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_needs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_needs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_needs_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_needs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_needs_title'))
        batch_op.drop_index(batch_op.f('ix_user_needs_id'))

    op.drop_table('user_needs')
    # ### end Alembic commands ###
