"""add article table

Revision ID: f0bfa32e3874
Revises: c4659b16c143
Create Date: 2024-08-08 10:54:51.358961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bfa32e3874'
down_revision = 'c4659b16c143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fk_business_category_id', sa.Integer(), nullable=True),
    sa.Column('fk_author_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['fk_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_business_category_id'], ['business_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_id'))

    op.drop_table('article')
    # ### end Alembic commands ###
